### ISSUE TITLE
All the constants are returning null and I don't know why

### ISSUE THREAD

**Issue by rhonalejandro** [davidlares/zebra-emdk-barcode#1]
In the onClick method of the corresponding class, a problem has been identified where the variable Constants.emdkManager returns null when it is expected to be initialized correctly. 

    @Override
    public void onClick(View view) {
        Log.d("TestApp", "Handling the click event");
        switch(view.getId()) {
            case R.id.startScanner:
                if(Constants.emdkManager != null) {
                    this.bridge.startScanner();
                }else{
                    Log.d("TestApp", "Constants.emdkManager null"); 

                }
                break;
            case R.id.stopScanner:
                if(Constants.emdkManager != null) {
                    this.bridge.stopScanner();
                }
                break;
        }
    }
    
    i have a TC15 zebra

**Comment by davidlares** [comment]
Hello buddy, there are a lot of possible vectors you need to re-evaluate and share to help you. 

I researched and noted that Zebra's TC15 supports EMDK only on devices with Android 13+. If your project is only intended for barcode scanning I highly recommend the DataWedge API, this is way more direct than using EDMK.

Be aware of the Java patterns used in the project, it heavily relies on Singleton and Observer patterns, this approach can be helpful for manual debugging. Also, in some scenarios, you'll need to use Threads to print out the barcode value in a TextView or related. All variables were intentionally made static and initialized to null for reutilization, nothing else.

Hoping this helps.

**Comment by rhonalejandro** [comment]
Hello, thank you very much for your answer, I will investigate how API DataWedge works, what I need is an application that reads the barcodes pdf417 of the costarricences identifications, it has cost me a little to make the TC15 to activate the reader, if you know any method to achieve that would be great, thank you very much for everything,

**Comment by davidlares** [comment]
You can read barcodes using known libraries for Android, many of which are camera-based. 

However, if you're willing to stick with Zebra software solutions, you can first check what's supported for your device, this includes Android versions for a proper EMDK installation at first. DataWedge is pretty much present everywhere, but it's more straightforward. Check the docs and follow the guides in there.

**Comment by rhonalejandro** [comment]
Yeap I know it's possible to read PDF417 with Android libraries, the issue is Costa Rica's ID document. Here's an example for you to see that it's a real challenge jajajajaja.
![imagen_2024-03-20_120825533](https://github.com/davidlares/zebra-emdk-barcode/assets/65178538/ee1d98bc-049d-446a-a813-239e86e14eb7)
